sudo: required
services:
  - docker

script:
  - docker build -t projectaetos/aetos-server ./server
  - docker images projectaetos/aetos-server
  
after_failure: $TRAVIS_TEST_RESULT

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

deploy:
  provider: script
  script: docker push projectaetos/aetos-server 
  on:
    branch: master
