sudo: required
services:
  - docker

script:
  - docker build -t projectaetos/aetos-server ./server
  - docker images projectaetos/aetos-server
  
after_failure: $TRAVIS_TEST_RESULT

before_deploy:
  - docker login -u jaycog44 -p 9335Dqi2W2n2uDs

deploy:
  provider: script
  script: docker push projectaetos/aetos-server 
  on:
    branch: master
